### ISSUE TITLE
The Adh-hoc contribution logger counts contributor badges

### ISSUE THREAD

**Issue by adamlofting** [mozilla/mozbadging#11]

**Comment by adamlofting** [comment]
@christensenep this looks great: https://github.com/mozilla/adhoctribution/pull/7 just one nit that I can see via github.

Related thoughts:
1. Are we spinning up a staging badgekit API I can test this against? Otherwise I can install something locally but don't know the system well.
2. This solves the MVP version, and I don't think we should complicate this now. But next iteration would be that the badges are flagged as contributor badges within badges.m.o so that the list of what counts as a contributor badge doesn't have to be managed in adhoctribution as well.

**Comment by ghost** [comment]
1) We've got one!  It's at https://badgekit-api-mozilla.mofostaging.net.  Prod is at https://badgekit-api-mozilla.mofoprod.net for the time being (we may move to a more pretty domain, though since it isn't an end-user-facing product JP kinda likes the idea of it living there, which I'm fine with.)

2) I 100% agreed with this when I started working on this PR, though when I started adding the various adhoctribution-specific fields (the data bucket and description fields specifically), I started wondering if maybe it wasn't so terrible for this list to live here...

...But nah, it's probably terrible.  In any case, yeah, it's certainly true we'd want a way to manage this list from within badges.m.o in some way, regardless.

**Comment by adamlofting** [comment]
With that last tweak I just commented on the PR, I think we can say the MVP version of this is ready. 

We can upgrade how this works when we solve #8 within the badges UX.
