### ISSUE TITLE
Identify site page needs for badges.m.o.

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#17]
I was talking with a potential designer for the badges.m.o. project and we discussed these page needs for the refreshed badges.m.o. (I think we need an “earn” stream (for Mozillian earners) and an “issue” stream (for badge creators) and would like your thoughts.)
- [ ] Homepage
- [ ] Issue flow (pages TBD)
- [ ] Available badges overview
- [ ] Earned badges: overall badges-issued-to date stats page
- [ ] Earned badges overview page (log in state?)
- [ ] Tag page
- [ ] Team page?
- [ ] FAQ/ABOUT

I can plan to create a rough sitemap and let me know what is missing. Thanks @christensenep @andrewhayward @davidascher.

**Comment by emgollie** [comment]
Friendly check-in on additional pages we need to be considering. Thanks in advance @christensenep @andrewhayward @davidascher.

**Comment by andrewhayward** [comment]
Has anyone looked over what is provided by the current badges.m.o? Based purely on the codebase, there seems to be a lot going on; we should probably make sure that if we do drop functionality, it's for considered and planned reasons, rather than because we're just not aware of it. Might it be worth trying to find out from current users what they do and don't like about the current offering, and what they would like to see change?

For example, do we care about displaying which badges users have earned? Do users care about it? Not all earners necessarily have accounts, and it's not currently the primary purpose of the site. But if we are going to be showing this sort of information, should badges.m.o also be a backpack provider? Is showing the stream of awarded badges overwhelming, or does it actually push people to earn things?

Seems to me like there's a lot of research needed, and I'm not clear if we've done it or not. Don't s'pose you know anyone who's good at community/user research, @emgollie? :wink:

**Comment by emgollie** [comment]
Thanks @andrewhayward. @zzzndr and I took a stab at characterizing current pages, and I agree that the next step is user feedback around areas of particular importance (I'd also like to bring a list and/or sitemap to some of our internal testers as a conversation starter). 

We can discuss during tomorrow's team meeting, and in the meantime, the no. 1 thing I've heard from Mozilla issuers is the importance of being able to view badges issued information. Many currently feel that once a badge is issued it is beyond their purview. They're eager for post-issuance information, including who has claimed their badges and similar badges. One example that I heard today: "I've been awarding the community superstar badges lately, and I can't (AFAIK) search to see who already has them."

**Comment by andrewhayward** [comment]
Regarding your final point, I was about to say "You mean [a page like this](https://badges.mozilla.org/en-US/badges/badge/Community-building-rockstar/awards)?" But then I looked at the page and realised it's broken. It's also several clicks through to that page, and not immediately obvious, so even if it was working, it's no great surprise if people don't know about it.

Regardless, there's definitely a lot we can do to surface how popular a badge is, what sort of traction it's getting, etc, that isn't currently being done. There's a lot of scope for all sorts of data visualisation if we want to run with it.

**Comment by davidascher** [comment]
yeah, a page like that + some of the metadata surfaced, so people know
- what those people did
- how they can apply for one

**Comment by emgollie** [comment]
Per today's Grow Mozilla meeting, I'm starting to publicize this short survey internally for information collection with internal issuers and earners: http://bit.ly/TP0Y3q 

Stay tuned for analysis.
