### ISSUE TITLE
Ability to create "contributor" badges in badgekit api (and hopefully badges.mozilla.org) that will automatically log awardees on Adam's adhoctribution site.

### ISSUE THREAD

**Issue by davidascher** [mozilla/mozbadging#2]

**Comment by adamlofting** [comment]
This could be push or pull between the two platforms so we should decide on the best route to do this. I think the main options are: 
1. badgekit webhooks ping a (currently non-existent) API endpoint on adhoctribution
2. badgekit API exposes a means of querying this data and adhoctribution periodically pulls from this
3. a (currently non-existent) third place stores the data and mozbadging and adhoctribution data both push to this, or it pulls from them. 

My thoughts:
1. is more work for me personally, but this could distribute the initial load so together we can ship something quickly
3. makes more sense in the future when the badgekit api could issue automated badges at scale (for things we wouldn't classify as 'ad-hoc') but I think is over-complicating things right now.

**Comment by ghost** [comment]
1) Is what I had in mind, particularly since we're going to be having multiple badging platforms, potentially for a while.  It seems a lot easier to make sure both of them know how to call a webhook when a badge is awarded, rather than keeping them both up to date with all the details of how we want to handle various types of badge award.  We can either split the work, or I can do the API work myself if you're too busy, either way works for me.

That being said, it would actually be possible to do things in adhoctribution alone right now without any actual badgekit api changes, via method 2).  It doesn't have the greatest filters for fetching the instances of particular badge (read: it has no filters at all), so you'd have to sort through a lot of data each time you call it (there are timestamps on the badges, though, which would make filtering them pretty simple at least).

I actually started that last paragraph intending to mostly dismiss the idea of 2), but now I'm sort of leaning toward that.  Heh.

**Comment by davidascher** [comment]
with 1), i think the auth problem is slightly trickier, as we likely need
shared secrets or equivalent to avoid corrupting the contribution data.  2)
requiring only read-only access of public data, feels less risky.

Also, note that we know we're going to want to make simple dashboards of
badges issued per various-kinds-of-categories, which I expect might need
similar routes.

**Comment by ghost** [comment]
We actually have a pretty good shared-secret-per-consumer system set up already in badgekit api, but it still is a bit more work to get this set up on the webhook's end, yeah.  It seems so easy to go the 2) route that we might as well just go that way, and if it ends up becoming problematic for any reason, we can switch to something more sophisticated.

**Comment by davidascher** [comment]
Not sure if we want to talk about it in this issue, but I'd like to see a paper napkin quality architectural diagram for the proposed "augmented" badges.mozilla.org.

In particular, I'd like to understand whether we're going with a front-end proxy that's routing requests to different apps (and if so, how do we want to handle auth (e.g. all auths are using the same persona 'realm'; how we think about deployment/ops (given that I expect the django badges.mozilla.org might well use a different deployment model than our typical puppet scripts, etc.)

**Comment by adamlofting** [comment]
I will turn this into granular actions, then we can close this discussion.

**Comment by adamlofting** [comment]
Closing this one, as we have an MVP solution.
For now this works by maintaining a list of 'which badges are contributor badges' within adhoctribution, and fetching data from badgekit-api for them.
We can iterate on this when we work out the UX for #8
