### ISSUE TITLE
Create contributor counting/practices working group

### ISSUE THREAD

**Issue by emgollie** [mozilla/mozbadging#9]
_Is there someone (from CBT?) on point re: overall badge system design for contributors (what counts for what?) or at least to coordinate mini-system design across Mozilla groups using badges (e.g. MDN, Wm.org)?_

I propose creating a group of people who meet regularly to discuss and create promoted practices around this (suggest David Boswell and/or Larissa Shapiro, Geoffrey, and @adamlofting to start).

**Comment by davidascher** [comment]
+1

**Comment by adamlofting** [comment]
Sounds good. Let's discuss on our call today as I think the fuzzyness in this area comes from the badges/counting overlap that we're trying to join up.

Existing CBT meetings are a good forum for some of this but there might be another co-ordination point needed.

(For discussion) I think the two objectives are:
1. Connect the MozBadges summer roadmap to the CBT counting and recognition plans
2. Provide some higher level guidance and promoted practices for anyone at Mozilla who wants to implement badges in another system, like MDN. Or is the question here specifically around issuing badges that enable us to count contribution?

Do those sound right?

**Comment by davidwboswell** [comment]
I'm happy to take part in these discussions and think coordinating closely across MoCo and MoFo about this is a good idea.

In terms of creating a new working group, have we decided that none of the existing working groups are the right fit?  We might be able to get more leverage making use of an existing group.

If we want to create a new group, that's fine.  Let's make sure to make it discoverable to the people doing community building work and report back on progress regularly to the larger group.

**Comment by adamlofting** [comment]
Thanks @davidwboswell, we think the missing piece here is "Counting contributors _with_ badges" as it overlaps a few of the working groups. 

We (all Moz) have been thinking about 'badges for recognition', and thinking about 'how we count contributors' but the idea of 'counting contributors _with badges_' has been theoretical until now because the platform to do this didn't exist. As this roadmap makes that possible, we want keep the things aligned.

This might not need something as formal as another working group, but perhaps a regular check-in with people across the existing working groups to make sure this roadmap is meeting the right requirements of each of the groups.

I'll start that thread and we can work out the best format from there.

**Comment by adamlofting** [comment]
In the call related to this, we didn't feel another working group was required here. But that this work on badges.m.o should continue to loop back into the existing CBT working groups to share progress and to get feedback on development: 

https://etherpad.mozilla.org/counting-contributors-with-badges
